### ISSUE TITLE
validate_doc_update()'s userCtx object is missing the `db` param.

### ISSUE THREAD

**Issue by tyler-johnson** [pouchdb/express-pouchdb#218] opened 2015-07-13 23:16 UTC
This is really an issue for [pouchdb-validation](https://www.npmjs.com/package/pouchdb-validation), but I'm not exactly sure where to put it, so I figured this was the next best place. Please let me know if I should move this.

According to [CouchDB's documentation](http://docs.couchdb.org/en/stable/json-structure.html#user-context-object), the `userCtx` object, the third argument for `validate_doc_update()` should have a `db` parameter. When express-pouchdb runs the function, the `db` value is undefined.

I happen to need the database name to confirm a few field values in documents. Is there a different way to get it? Otherwise, it would be great to get that included!

**Comment by marten-de-vries** [comment] 2015-07-14 13:32
Thanks for reporting!

Actually, the problem is that express-pouchdb passes in a ``userCtx`` object that's missing a ``db`` property. (The ``userCtx`` object isn't generated by pouchdb-validation if it's passed in, which express-pouchdb does).

I think it could be fixed in https://github.com/pouchdb/express-pouchdb/blob/master/lib/utils.js#L48 , by getting the db name from the url in the ``req`` object (or otherwise it could be manually passed into that function as a new argument).

And for future reference: pouchdb-validation and a bunch of other plugins of mine are hosted [on Launchpad](https://launchpad.net/python-pouchdb/). Their code [is in a git repo hosted there](https://git.launchpad.net/python-pouchdb/).

**Comment by tyler-johnson** [comment] 2015-07-14 15:48
Okay cool thanks! I will try to get a pull-request submitted later today.

**Comment by nolanlawson** [comment] 2015-08-23 19:24
fixed by 841f75f8f33e5f356792ee5f123605903fcbaafd

**Closed by nolanlawson** 2015-08-23 19:24 UTC
