### ISSUE TITLE
Object [object Promise] has no method 'on' at changes

### ISSUE THREAD

**Issue by denis-sokolov** [pouchdb/express-pouchdb#202] opened 2015-04-10 08:11 UTC
I am using the `pouchdb-server`, and I experience the following error deep from internals of `express-pouchdb` ([full error traceback](https://gist.githubusercontent.com/denis-sokolov/052cfc75077bb4e77095/raw/1abf7fe49dfdd498393278b6ff7b9086e3c0df29/gistfile1.sh)):
```
TypeError: Object [object Promise] has no method 'on'
    at changes (.../node_modules/pouchdb-server/node_modules/express-pouchdb/lib/routes/changes.js:56:35)
```
The file in question uses pouch according to [the documentation](http://pouchdb.com/api.html#changes):
```javascript
req.db.changes(req.query).on('complete', function (complete) {
```
However, I have investigated what is the `db.changes` returning, and it does, indeed return a regular promise in `express-pouchdb` under my circumstances. I have investigated further and found that `db.changes` is actually [wrapped around with `pouchdb-wrappers`](http://bazaar.launchpad.net/~marten-de-vries/python-pouchdb/0.x/view/head:/js/pouchdb-wrappers/index.js#L195). I am not sure what the wrapper is supposed to do, but it [calls `callHandlers`](http://bazaar.launchpad.net/~marten-de-vries/python-pouchdb/0.x/view/head:/js/pouchdb-wrappers/index.js#L199), and [that function](http://bazaar.launchpad.net/~marten-de-vries/python-pouchdb/0.x/view/head:/js/pouchdb-wrappers/index.js#L422) in turn clearly returns a regular promise, which is not what `db.changes` is supposed to return.

Currently I can't use `pouchdb-server`/`express-pouchdb` at all, as it crashes pretty much right away after start.

**Comment by nolanlawson** [comment] 2015-04-10 10:21
`pouchdb-wrappers` was written by @marten-de-vries, looks like maybe it needs a fix in cases where it has to export an object that's both a promise and an event emitter?

**Comment by marten-de-vries** [comment] 2015-04-10 13:32
Why haven't we seen this before when running the PouchDB test suite/couchdb-harness against pouchdb-server? Might be nice to know, since I would've expected this to have been caught earlier.

Actually, ``pouchdb-wrappers`` works fine, considering [this (tested) piece of code in transform-pouch](https://github.com/nolanlawson/transform-pouch/blob/master/index.js#L111) works. The problem is that some of the modules that use pouchdb-wrappers, other than transform-pouch, forget about the event emitter stuff and don't copy it over at least. I think this time pouchdb-security is to blame, although I should check pouchdb-validation, http-pouchdb, pouchdb-size, pouchdb-system-db & pouchdb-auth to be safe too. (All are used, directly or indirectly, by express-pouchdb.)

As for a workaround, try disabling the file 'security' [as explained in the README.md](https://github.com/pouchdb/express-pouchdb#example-2). If that works, please do report back since that would confirm the above.

**Comment by denis-sokolov** [comment] 2015-04-10 13:55
Confirmed.

I have changed `pouchdb-server` by [disabling auth](https://github.com/pouchdb/pouchdb-server/compare/master...Useclark:disable-auth) and all my crashes are gone.

Until further development I will be using the forked version as a temporary workaround.
Thank you!

**Comment by denis-sokolov** [comment] 2015-04-10 14:00
Scratch that, I actually need auth modules for my purposes. I will be very actively watching this for updates.

**Comment by nolanlawson** [comment] 2015-04-10 14:11
@marten-de-vries does that would explain why the tests didn't find it, since we run in admin party mode?

**Comment by denis-sokolov** [comment] 2015-04-10 14:17
No, I was running in admin party this whole time. This is a testing environment. At the same time I was creating users and logging them in. Perhaps I misunderstand how I should be using PouchDB?
I will consider any and all suggestions to try things out and experiment.

Of course, the server should not crash regardless of my weird use cases.

**Comment by gr2m** [comment] 2015-04-25 12:53
Here is a test case for the problem, and a fork that includes a fix:
https://github.com/pouchdb/pouchdb-server/issues/97

**Comment by marten-de-vries** [comment] 2015-04-25 16:34
Should be fixed. See for more info https://github.com/pouchdb/pouchdb-server/issues/97 .

**Closed by marten-de-vries** 2015-04-25 16:34 UTC
